---
kind: pipeline
name: default

steps:
  - name: now
    image: one000mph/drone-now        # Use one000mph's version as lucaperret's is outdated
    environment:
      NOW_TOKEN:
        from_secret: now_token    # Refers to a secret in your drone repo titled "NOW_TOKEN"
    settings:
      secret: [now_token]           # Refers to the above environment variable
      deploy_name: example          # The name of your vercel project
      prod: true                    # Leave this if you want to deploy to production, remove to disable production
      directory: public             # Only if you've pre-rendered the page. Normally you let vercel handle this